
﻿#INSERÇÃO DOS ESTADOS

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('AC', '1');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('AL', '2');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('AP', '3');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('AM', '4');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('BA', '5');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('CE', '6');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('DF', '7');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('ES', '8');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('GO', '9');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('MA', '10');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('MT', '11');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('MS', '12');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('MG', '13');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('PA', '14');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('PB', '15');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('PR', '16');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('PE', '17');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('PI', '18');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('RJ', '19');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('RN', '20');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('RS', '21');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('RO', '22');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('RR', '23');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('SC', '24');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('SP', '25');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('SE', '26');

INSERT INTO UF (DESCRICAO, CODESTADO) VALUES ('TO', '27');


#INSERÇÃO DOS APLICATIVOS

INSERT INTO APLICATIVO (CODAPLICATIVO, DESCRICAO) VALUES ('1','ATS');

INSERT INTO APLICATIVO (CODAPLICATIVO, DESCRICAO) VALUES ('2', 'YUNES');



#INSERÇÃO DAS ORIGENS

INSERT INTO ORIGEM (CODORIGEM, DESCRICAO) VALUES ('1','EMAIL');

INSERT INTO ORIGEM (CODORIGEM, DESCRICAO) VALUES ('2','TELEFONE');

INSERT INTO ORIGEM (CODORIGEM, DESCRICAO) VALUES ('3','SKYPE');

INSERT INTO ORIGEM (CODORIGEM, DESCRICAO) VALUES ('4','VERBAL');

INSERT INTO ORIGEM (CODORIGEM, DESCRICAO) VALUES ('5','WEB');



#INSERÇÃO DOS STATUS

INSERT INTO STATUS (CODSTATUS, DESCRICAO) VALUES ('1','ABERTO');

INSERT INTO STATUS (CODSTATUS, DESCRICAO) VALUES ('2','EXECUCAO');

INSERT INTO STATUS (CODSTATUS, DESCRICAO) VALUES ('3','PENDENTE');

INSERT INTO STATUS (CODSTATUS, DESCRICAO) VALUES ('4','CONCLUIDO');

INSERT INTO STATUS (CODSTATUS, DESCRICAO) VALUES ('5','CANCELADO');



#INSERÇÃO DAS PRIORIDADES

INSERT INTO PRIORIDADE (CODPRIORIDADE, DESCRICAO) VALUES ('1','NORMAL');

INSERT INTO PRIORIDADE (CODPRIORIDADE, DESCRICAO) VALUES ('2','URGENTE');



#INSERÇÃO DAS TIPO ATENDIMENTO

INSERT INTO TIPO_ATENDIMENTO(CODTIPOATENDIMENTO, DESCRICAO) VALUES ('1','SUPORTE');

INSERT INTO TIPO_ATENDIMENTO(CODTIPOATENDIMENTO, DESCRICAO) VALUES ('2','TREINAMENTO');

INSERT INTO TIPO_ATENDIMENTO(CODTIPOATENDIMENTO, DESCRICAO) VALUES ('3','REUNIÃO');

INSERT INTO TIPO_ATENDIMENTO(CODTIPOATENDIMENTO, DESCRICAO) VALUES ('4','CONSULTORIA');

INSERT INTO TIPO_ATENDIMENTO(CODTIPOATENDIMENTO, DESCRICAO) VALUES ('5','ATUALIZAÇÃO');



#INSERÇÃO DOS TIPO_USUARIO

INSERT INTO TIPO_USUARIO(CODTIPOUSUARIO, DESCRICAO) VALUES ('1','ROLE_SUPORTE');

INSERT INTO TIPO_USUARIO(CODTIPOUSUARIO, DESCRICAO) VALUES ('2','ROLE_ATENDENTE');

INSERT INTO TIPO_USUARIO(CODTIPOUSUARIO, DESCRICAO) VALUES ('3','ROLE_ADMINISTRADOR');
